export type Recipe = {
  id: string;
  title: string;
  description: string;
  image: string;
  cookingTime: number; // in minutes
  servings: number;
  difficulty: 'easy' | 'medium' | 'hard';
  ingredients: {
    name: string;
    amount: string;
  }[];
  instructions: string[];
  tips?: string[];
};

export const recipes: Recipe[] = [
  {
    id: '1',
    title: 'Classic Margherita Pasta',
    description: 'A simple yet elegant Italian pasta dish with fresh tomatoes, basil, and mozzarella.',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=300&fit=crop',
    cookingTime: 20,
    servings: 4,
    difficulty: 'easy',
    ingredients: [
      { name: 'Fresh pasta', amount: '400g' },
      { name: 'Fresh tomatoes', amount: '500g' },
      { name: 'Fresh mozzarella', amount: '250g' },
      { name: 'Fresh basil', amount: '1 bunch' },
      { name: 'Olive oil', amount: '4 tablespoons' },
      { name: 'Garlic cloves', amount: '2' },
      { name: 'Salt and pepper', amount: 'to taste' },
    ],
    instructions: [
      'Bring a large pot of salted water to boil.',
      'Cut tomatoes in half and remove excess seeds.',
      'Heat olive oil in a pan and sauté minced garlic.',
      'Add tomatoes to the pan and cook for 10 minutes on medium heat.',
      'Cook pasta according to package directions until al dente.',
      'Drain pasta and toss with the tomato sauce.',
      'Top with fresh mozzarella and basil.',
      'Drizzle with olive oil and serve immediately.',
    ],
    tips: [
      'Use San Marzano tomatoes for the best flavor.',
      'Add pasta water to the sauce if it\'s too thick.',
      'Fresh basil should be added at the last moment for maximum flavor.',
    ],
  },
  {
    id: '2',
    title: 'Thai Green Curry',
    description: 'A vibrant and aromatic Thai curry with creamy coconut milk and fresh vegetables.',
    image: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e4e31?w=500&h=300&fit=crop',
    cookingTime: 35,
    servings: 4,
    difficulty: 'medium',
    ingredients: [
      { name: 'Chicken breast', amount: '500g' },
      { name: 'Coconut milk', amount: '400ml' },
      { name: 'Thai green curry paste', amount: '3 tablespoons' },
      { name: 'Bell peppers', amount: '2' },
      { name: 'Thai basil leaves', amount: '1 handful' },
      { name: 'Fish sauce', amount: '2 tablespoons' },
      { name: 'Sugar', amount: '1 teaspoon' },
      { name: 'Lime juice', amount: '2 tablespoons' },
    ],
    instructions: [
      'Cut chicken into bite-sized pieces.',
      'Heat coconut milk in a large pan over medium heat.',
      'Add curry paste and stir until fragrant (about 2 minutes).',
      'Add chicken pieces and cook until done (8-10 minutes).',
      'Add bell peppers and cook for 5 more minutes.',
      'Season with fish sauce, sugar, and lime juice.',
      'Add Thai basil leaves at the end.',
      'Serve over jasmine rice.',
    ],
    tips: [
      'Don\'t skip the fish sauce - it adds authentic flavor.',
      'You can adjust the curry paste amount based on your heat preference.',
      'Add vegetables in stages based on cooking time.',
    ],
  },
  {
    id: '3',
    title: 'Chocolate Lava Cake',
    description: 'A decadent dessert with a molten chocolate center that flows when you cut into it.',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&h=300&fit=crop',
    cookingTime: 25,
    servings: 2,
    difficulty: 'hard',
    ingredients: [
      { name: 'Dark chocolate', amount: '150g' },
      { name: 'Butter', amount: '100g' },
      { name: 'Eggs', amount: '2' },
      { name: 'Sugar', amount: '50g' },
      { name: 'Flour', amount: '25g' },
      { name: 'Vanilla extract', amount: '1 teaspoon' },
      { name: 'Pinch of salt', amount: '1 pinch' },
    ],
    instructions: [
      'Preheat oven to 220°C (425°F).',
      'Chop chocolate and place in a heatproof bowl with butter.',
      'Heat over simmering water until melted and smooth.',
      'In another bowl, whisk eggs with sugar until pale.',
      'Fold chocolate mixture into egg mixture.',
      'Gently fold in flour, vanilla, and salt.',
      'Pour into prepared ramekins.',
      'Bake for 12-14 minutes until the cake is set but the center is still soft.',
      'Let cool for 2 minutes, then invert onto plates.',
    ],
    tips: [
      'The centers should still be liquid - timing is crucial!',
      'Butter and flour the ramekins well to prevent sticking.',
      'You can prepare the batter in advance and refrigerate until ready to bake.',
    ],
  },
  {
    id: '4',
    title: 'Mediterranean Salad',
    description: 'A fresh and light salad packed with vegetables, feta cheese, and olives.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=300&fit=crop',
    cookingTime: 15,
    servings: 4,
    difficulty: 'easy',
    ingredients: [
      { name: 'Cherry tomatoes', amount: '300g' },
      { name: 'Cucumber', amount: '1' },
      { name: 'Red onion', amount: '1/2' },
      { name: 'Kalamata olives', amount: '150g' },
      { name: 'Feta cheese', amount: '150g' },
      { name: 'Fresh parsley', amount: '1 handful' },
      { name: 'Olive oil', amount: '5 tablespoons' },
      { name: 'Lemon juice', amount: '2 tablespoons' },
    ],
    instructions: [
      'Cut cherry tomatoes in half.',
      'Dice cucumber into chunks.',
      'Slice red onion thinly.',
      'Combine tomatoes, cucumber, and onion in a large bowl.',
      'Add olives and crumbled feta cheese.',
      'Whisk olive oil and lemon juice together.',
      'Pour dressing over salad and toss gently.',
      'Top with fresh parsley and serve immediately.',
    ],
    tips: [
      'This salad is best served fresh, but can be made ahead without the dressing.',
      'You can add chickpeas for protein.',
      'Try different varieties of olives for different flavors.',
    ],
  },
  {
    id: '5',
    title: 'Homemade Pizza Margherita',
    description: 'Make your own pizza from scratch with crispy crust and fresh toppings.',
    image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=500&h=300&fit=crop',
    cookingTime: 45,
    servings: 2,
    difficulty: 'medium',
    ingredients: [
      { name: 'All-purpose flour', amount: '300g' },
      { name: 'Yeast', amount: '7g' },
      { name: 'Warm water', amount: '200ml' },
      { name: 'Salt', amount: '7g' },
      { name: 'Olive oil', amount: '20ml' },
      { name: 'Tomato sauce', amount: '200ml' },
      { name: 'Fresh mozzarella', amount: '200g' },
      { name: 'Fresh basil', amount: '1 bunch' },
    ],
    instructions: [
      'Mix warm water with yeast and let sit for 10 minutes.',
      'Combine flour and salt in a bowl.',
      'Add yeast mixture and olive oil to flour.',
      'Knead for 10 minutes until smooth and elastic.',
      'Let dough rise for 1 hour until doubled.',
      'Divide dough in half and shape into pizzas.',
      'Spread tomato sauce on each pizza.',
      'Top with mozzarella cheese.',
      'Bake at 220°C for 15-20 minutes until crust is golden.',
      'Add fresh basil after baking.',
    ],
    tips: [
      'Use a pizza stone for crispier crust.',
      'Don\'t overload with toppings.',
      'Oven temperature is crucial for good pizza.',
    ],
  },
  {
    id: '6',
    title: 'Grilled Salmon with Lemon Butter',
    description: 'A restaurant-quality salmon dish with a delicate lemon butter sauce.',
    image: 'https://images.unsplash.com/photo-1580959375944-abd7e991f971?w=500&h=300&fit=crop',
    cookingTime: 30,
    servings: 2,
    difficulty: 'easy',
    ingredients: [
      { name: 'Salmon fillets', amount: '2 (6 oz each)' },
      { name: 'Butter', amount: '50g' },
      { name: 'Fresh lemon juice', amount: '2 tablespoons' },
      { name: 'Garlic cloves', amount: '2' },
      { name: 'Fresh dill', amount: '1 tablespoon' },
      { name: 'Salt and pepper', amount: 'to taste' },
      { name: 'Olive oil', amount: '2 tablespoons' },
    ],
    instructions: [
      'Preheat grill to medium-high heat.',
      'Pat salmon dry and season with salt and pepper.',
      'Brush grill grates with olive oil.',
      'Grill salmon skin-side down for 6-8 minutes.',
      'Flip and grill for another 4-5 minutes.',
      'In a small pan, melt butter and sauté minced garlic.',
      'Add lemon juice and dill to butter sauce.',
      'Drizzle sauce over salmon and serve.',
    ],
    tips: [
      'Don\'t flip the salmon too often - it needs time to develop a nice crust.',
      'You can also cook this in a pan if you don\'t have a grill.',
      'Watch the internal temperature - it should reach 145°F.',
    ],
  },
];
